### ISSUE TITLE
Content on the events pages

### ISSUE THREAD

**Issue by propensive** [larsrh/typelevel-beta#1]

**Comment by milessabin** [comment]
Amongst other things we need,
+ Travel info
+ Accommodation info
+ Info on apply for attendance assistance
+ Sponsor logos
+ Call for sponsors/donations

The call for speakers needs,
+ Info about mentoring availability
+ Number and length(s) of speaker slots

The call for participation needs,
+ Vague outline of activity on day 2.

**Comment by larsrh** [comment]
In c61982a I've removed the filler content and added some stubs for the summits.

@bmc: Could you please send us the text for the cross-promotion with NE Scala?
@hamnis, @teigen: Same for flatMap.

**Comment by bmc** [comment]
Draft language between reviewed now.

**Comment by bmc** [comment]
Here's the language:

Plan to hang around after the Typelevel Summit, because this year, [Northeast Scala Symposium 2016](http://www.nescala.org) will be held at the _same_ location on March 4th and 5th. RSVPs open January 16th.

**Comment by hamnis** [comment]
We are dicussing the text now.

**Comment by hamnis** [comment]
```Arriving early for the Typelevel Summit? flatMap(Oslo) will be held at the same location on May 2nd and 3rd. RSVPs and ticket sales are now open```

**Comment by larsrh** [comment]
I've added the content to our "old" site (front page) now. As soon as we launch the new site it will appear there, too. Apologies for the delay.

**Comment by larsrh** [comment]
Promo now on the new site, too: typelevel/typelevel.github.com@76e92f0
