### ISSUE TITLE
License information on the pictures of Oslo and Philly

### ISSUE THREAD

**Issue by propensive** [larsrh/typelevel-beta#2]

**Comment by larsrh** [comment]
Looks like we're going to need new pictures. I suggest these:

* [Philadelphia](https://flic.kr/p/c2gLD9)
* [Oslo](https://flic.kr/p/vT6Ajg)

**Comment by larsrh** [comment]
Wait, I found the current Philadelphia picture on [Flickr](https://flic.kr/p/tCR6T1), too.
