### ISSUE TITLE
Information about speaker/attendee assistance

### ISSUE THREAD

**Issue by davegurnell** [larsrh/typelevel-beta#6]
Here's what I have at the moment:

- A [draft blog post][post] about speaker assistance (doesn't mention attendee assistance yet)
- A [draft google form][form] for people to apply for assistance and bursaries

I'll brush these up and PR them. Comments welcome here.

[post]: https://gist.github.com/davegurnell/b960c48322f7a6f218bb
[form]: https://docs.google.com/a/underscoreconsulting.com/forms/d/1hhia7etHm_UT4WnQS7JTyGE03z-2-T1xJGujOkvacjs/viewform

**Comment by larsrh** [comment]
Closed by #8.
